plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDirs = ['app/src']
        }
        resources {
            srcDirs = ['app/resources']
        }
    }
}

application {
    mainClass = 'sp.JavaFXGUI.SaltAndPepperApp'
}

javafx {
    version = '21.0.2'
    modules = ['javafx.controls', 'javafx.fxml']
}

run {
    standardInput = System.in
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:8.3.0'
}

javadoc {
    source = sourceSets.main.allJava
    classpath = sourceSets.main.compileClasspath
    destinationDir = file("$buildDir/docs/javadoc")
}

tasks.register('publishDocs', Copy){
    dependsOn javadoc
    from "$buildDir/docs/javadoc"
    into "$projectDir/docs"
}

build.finalizedBy publishDocs